server:
  port: 8090
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        #namespace: 13484140-5de5-45d0-91a1-1504132e25c6
        server-addr: 39.103.124.8:8848
stock-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
#springboot 默认级别是info大于debug所以要指定
logging:
  level:
    com.tuling.openfeign: debug
#fegin局部日志
#feign:
#  client:
#    config:
#      stock-service:
#        loggerLevel: FULL
