server:
  port: 8099
spring:
  application:
    name: gateway
  cloud:
    #gateway配置
    gateway:

      #路由配置
      routes:
        - id: order_route
          uri: lb://order-service #需要转发的地址  lb loadbalanced 负载均衡策略
          predicates:
            - Path=/order-serv/** #路由到⬇️
            #http://localhost:8099/order-serv/order/add
             #http://localhost:8098/order-serv/order/add
            - After=2021-11-01T14:36:49.340+08:00[Asia/Shanghai] #当前访问时间之后可以访问
            # - Before=2021-11-01T14:36:49.340+08:00[Asia/Shanghai] #当前访问时间之前可以访问
            - Method=GET #get
          filters:
            - StripPrefix=1 #转发之前去掉第一层路径 去掉order-serv
      #跨域配置
      globalcors:
        cors-configurations:
          '[/**]':  #允许跨域访问资源
            allowedOrigins: "*"   #跨域允许
            allowedMethods:
              - GET
              - POST
    nacos:
      discovery:
        server-addr: 39.103.124.8:8848
        username: nacos
        password: nacos
    #sentinel配置
    sentinel:
      transport:
        dashboard: localhost:8080

